import 'dart:io';
import 'package:build_pipe/config/platform_specific_config.dart';
import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart' as yaml;

class AndroidPublishConfig {
  // 1. path to build file `e.g. build/ios/ipa/yourapp.ipa`
  String outputFilePath;
  String? credentialPath;
  // 3. Bundle id `com.example.app`
  String bundleID;
  String track;

  AndroidPublishConfig({
    required this.bundleID,
    required this.outputFilePath,
    required this.track,
    this.credentialPath,
  });

  /// Gets the path of the JSON credential file
  /// If the path is provided in the env, it will be
  /// read from the env, otherwise the default path
  /// will be provided.
  ///
  /// The default path is:
  /// ./private_keys/play_api_key.json
  String getCredentialPath() {
    String jcp = "";
    if (credentialPath != null && credentialPath!.isNotEmpty) {
      jcp = Platform.environment[credentialPath!] ?? "";
    }
    if (jcp.isEmpty) {
      jcp = p.join("private_keys", "play_api_key.json");
    }
    return jcp;
  }

  factory AndroidPublishConfig.fromMap(yaml.YamlMap data) {
    return AndroidPublishConfig(
      credentialPath: data["credentialPath"],
      track: data["releaseTrack"],
      bundleID: data["bundleID"],
      outputFilePath: data["outputFilePath"],
    );
  }

  static (bool, String?) isValid(yaml.YamlMap data, TargetPlatform tp) {
    if (!data.containsKey("bundleID") || data["bundleID"] == "") {
      return (false, "'bundleID' is missing from the publish config for ${tp.name}. The bundle id is structured as 'com.example.your_app'.");
    }

    if (!data.containsKey("releaseTrack") || data["releaseTrack"] == "") {
      return (false, "'releaseTrack' is missing from the publish config for ${tp.name}. It determines the the type of the release you plan to create, such as 'internal' or 'beta'.");
    }

    if (!data.containsKey("outputFilePath") || data["outputFilePath"] == "") {
      String examplePath = "build/app/outputs/bundle/release/app-release.aab";
      return (
        false,
        "'outputFilePath' is missing from the publish config for ${tp.name}. This is the path to the build file generated by the 'flutter build' command. e.g. $examplePath",
      );
    }

    return (true, null);
  }
}

class AndroidConfig {
  AndroidPublishConfig? publishConfig;

  AndroidConfig({this.publishConfig});
}
