import 'dart:convert';
import 'dart:io';

import 'package:build_pipe/config/config.dart';
import 'package:build_pipe/config/platform_specific_config.dart';
import 'package:build_pipe/utils/console.utils.dart';
import 'package:build_pipe/utils/process.utils.dart';
import 'package:yaml/yaml.dart' as yaml;

class IOSConfig {
  ApplePublishConfig? publishConfig;

  IOSConfig({this.publishConfig});
}

class MacOSConfig {
  ApplePublishConfig? publishConfig;

  MacOSConfig({this.publishConfig});
}

/// The publish config class, handling for both iOS and macOS
///
/// Contains the `upload` function to handle the upload process
class ApplePublishConfig {
  // 1. path to build file `e.g. build/ios/ipa/yourapp.ipa`
  String outputFilePath;
  // 2. App's Apple ID `App Store Connect > Your App > App Information > Apple ID`
  String appAppleID;
  // 3. Bundle id `com.example.app`
  String bundleID;
  // 4. API key `123XX1234X`
  String keyID;
  // 5. API issuer ID `App Store Connect > Integrations > App Store Connect API > Issuer ID`
  String issuerID;

  ApplePublishConfig({required this.keyID, required this.appAppleID, required this.bundleID, required this.issuerID, required this.outputFilePath});

  /// Checks if the given config in the `pubspec` is valid or not
  ///
  /// Should be called before the `fromMap` function
  static (bool, String?) isValid(yaml.YamlMap data, TargetPlatform tp) {
    if (!data.containsKey("keyID") || data["keyID"] == "" || !Platform.environment.containsKey(data["keyID"]) || Platform.environment["keyID"] == "") {
      return (
        false,
        "'keyID' env variable is missing from the publish config for ${tp.name} or invalid. You can get the key ID by creating an API key from 'App Store Connect' > 'Users & Access' > 'Integrations'.",
      );
    }

    if (!data.containsKey("issuerID") || data["issuerID"] == "" || !Platform.environment.containsKey(data["issuerID"]) || Platform.environment["issuerID"] == "") {
      return (
        false,
        "'issuerID' env variable is missing from the publish config for ${tp.name} or invalid. You can get the issuer ID by visiting 'App Store Connect' > 'Users & Access' > 'Integrations'.",
      );
    }

    if (!data.containsKey("appAppleID") || data["appAppleID"] == "" || !Platform.environment.containsKey(data["appAppleID"]) || Platform.environment["appAppleID"] == "") {
      return (
        false,
        "'appAppleID' env variable is missing from the publish config for ${tp.name} or invalid. You can get the apple ID of your app from the 'App Information' section of your app in App Store Connect.",
      );
    }

    if (!data.containsKey("bundleID") || data["bundleID"] == "") {
      return (false, "'bundleID' is missing from the publish config for ${tp.name}. The bundle id is structured as 'com.example.your_app'.");
    }

    if (!data.containsKey("outputFilePath") || data["outputFilePath"] == "") {
      String examplePath = "build/ios/ipa/yourapp.ipa";
      if (tp == TargetPlatform.macos) {
        examplePath = "build/macos/Build/Products/Release/yourapp.app";
      }
      return (
        false,
        "'outputFilePath' is missing from the publish config for ${tp.name}. This is the path to the build ${tp == TargetPlatform.macos ? "folder" : "file"} generated by the 'flutter build' command. e.g. $examplePath",
      );
    }

    return (true, null);
  }

  /// Converts the YAML map to an instance of [ApplePublishConfig]
  ///
  /// The data should first be validated with the `isValid` function
  factory ApplePublishConfig.fromMap(yaml.YamlMap data) {
    return ApplePublishConfig(
      appAppleID: Platform.environment[data["appAppleID"]]!,
      keyID: Platform.environment[data["keyID"]]!,
      issuerID: Platform.environment[data["issuerID"]]!,
      bundleID: data["bundleID"],
      outputFilePath: data["outputFilePath"],
    );
  }

  /// Uploads the build artifact to the iOS App Store
  Future<void> uploadToIOS({
    required BPConfig config,
  }) async {
    var iosOut = await ProcessHelper.runCommandUsingConfig(
      startMessage: "Starting to publish the iOS app...",
      errorMessage: "There was a problem in publishing the iOS app",
      successMessage: "√ iOS app is successfully published",
      executable: "xcrun",
      exitIfError: false,
      redactions: [
        appAppleID,
        issuerID,
        keyID,
      ],
      arguments: [
        "altool",
        "--upload-package",
        outputFilePath,
        "-t",
        'ios',
        "--apple-id",
        appAppleID,
        "--bundle-id",
        '"$bundleID"',
        "--apiKey",
        keyID,
        "--apiIssuer",
        issuerID,
        "--bundle-short-version-string",
        config.version,
        "--bundle-version",
        config.buildVersion,
        "--asc-public-id",
        issuerID,
        "--output-format",
        "json",
      ],
      config: config,
    );

    if (iosOut.$1 != 0 && iosOut.$2.isNotEmpty) {
      try {
        Map<String, dynamic> iosErr = jsonDecode(iosOut.$2[0]);
        if (iosErr.containsKey("product-errors")) {
          List<dynamic> peList = iosErr["product-errors"];
          for (var pe in peList) {
            Console.logError("-- ${pe["userInfo"]["NSLocalizedFailureReason"] ?? "-"}\n");
          }
        }
      } catch (_) {}
    }
  }
}
